### ISSUE TITLE
Cadastro de novos clientes

### ISSUE THREAD

**Issue by pedrohenriquebr** [pedrohenriquebr/target-bank-challenge#8]
Epic: #7 

### Description

Como desenvolvedor, gostaria de permitir o cadastro de novos clientes (Pessoa Física)
informando seus dados.

### Tasks

- [ ] Criar um método POST para solicitar os seguintes dados
- [ ] Retornar um Json com no mínimo os seguintes campos
- [ ] Validar consistência dos dados informados pelo cliente.
- [ ] Necessário ter 2 métodos auxiliares, um para listar UFS e outro para listar Cidades dada UF, a fim de facilitar o preenchimento.
- [ ] Para o banco de dados utilizado criar o modelo de dados e anexar no repositório todos
os scripts SQL.
