### ISSUE TITLE
S2: Plano Vip

### ISSUE THREAD

**Issue by pedrohenriquebr** [pedrohenriquebr/target-bank-challenge#9]
Epic: #7 

### Description

Como PO, gostaria de oferecer nosso 'plano vip' no cadastro de novos clientes, quando a
renda for igual ou superior a seis mil reais.

### Tasks

- [ ] No método de cadastro de cliente. Se o cadastro for concluído com sucesso e, renda
superior ou igual à 6k (Seis mil reais)
- [ ] Método GET para o app requisitar os detalhes do plano VIP.
- [ ] Método POST para o cliente confirmar que aceita o plano VIP.
